version: '3'

services:

  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    healthcheck: 
      test: ['CMD', 'mysqladmin', 'ping', '--silent']
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s
    networks: 
      - directus
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    depends_on:
      - mysql
    networks: 
      - directus
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    restart: always
    ports:
      - ${DIRECTUS_PORT}:${DIRECTUS_PORT}
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./snapshots:/directus/snapshots
    networks:
      - directus
    depends_on:
      - cache
      - mysql
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      DB_CLIENT: 'mysql'
      DB_HOST: 'mysql'
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASS}
      DB_DATABASE: ${MYSQL_DB}
      DB_PORT: ${MYSQL_PORT}

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'
      CACHE_AUTO_PURGE: 'true'
      CACHE_SYSTEM_TTL: '2m'
      CACHE_SCHEMA: 'false'
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true'

      PUBLIC_URL: ${PUBLIC_URL}

  graphiql:
    container_name: graphiql
    image: plutoz/graphiql
    depends_on:
      - directus
    ports:
      - ${GRAPHQL_PORT}:${GRAPHQL_PORT}
    environment:
      API_ENDPOINT: ${API_ENDPOINT}
    networks:
      - directus

networks:
  directus:
    driver: bridge